management:
  endpoints:
    jmx:
      exposure:
        exclude: '*'
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
server:
  error:
    include-message: always
  port: 9090
