management:
  endpoints:
    jmx:
      exposure:
        exclude: '*'
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
spring:
  data:
    mongodb:
      auto-index-creation: true
      database: jbcnconf
  jackson:
    default-property-inclusion: non_empty
server:
  error:
    include-message: always
# Custom properties
api-server:
  auth:
    client-id: 189e2d22-2da5-44fb-ab0a-d5a57fac4d50
  jwt:
    issuer: https://www.jbcnconf.com
    secret: bezKoderSecretKey
    ttl-millis: 3600

