name: Native
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        java:
          - 11
          - 16
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: '21.1.0'
          arch: 'amd64'
      - name: Build and Test
        run: ./gradlew -s --console=plain nativeTest
